name: Rust

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Build
        run: cargo build --verbose
        working-directory: ./api
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./api
